apiVersion: v1
kind: Service
metadata:
  name: {{ include "shop-db.name" . }}
  labels:
    {{- include "shop-db.labels" . | nindent 4 }}
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    {{- include "shop-db.selectorLabels" . | nindent 4 }}
