replicaCount: 1

image:
  repository: busybox
  tag: "1.36"
  pullPolicy: IfNotPresent

persistence:
  enabled: true
  storageClassName: ""
  accessMode: ReadWriteOnce
  size: 64Mi
  mountPath: /data
