{{- if and .Values.secret .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shop-api.credentialsSecret" . }}
  labels:
    {{- include "shop-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  PGRST_DB_URI: {{ printf "postgres://%s:%s@%s:5432/%s" (.Values.user | default "shop") (.Values.secret.password | default "shopdevpassword") (.Values.dbHost | default "backend-db") (.Values.database | default "shop") | quote }}
{{- end }}
