{{- if .Values.secret.create }}
{{- if not .Values.secret.data }}
{{- fail "secret.create is true but secret.data is empty" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nginx-demo.envSecretName" . }}
  labels:
    {{- include "nginx-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
