replicaCount: 1

extraEnv:
  LAB_NAME: dev
  FEATURE_ENABLED: "false"

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    memory: 128Mi

pageContent: |
  <h1>Hello from Updated Helm Lab</h1>

global:
  environment: dev
