replicaCount: 1

extraEnv:
  LAB_NAME: dev
  FEATURE_ENABLED: "false"

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    memory: 128Mi

pageContent: |
  <h1>Hello from {{ .Release.Name }} in {{ .Values.global.environment }}</h1>

extraConfigMaps:
  settings:
    ENVIRONMENT: "{{ .Values.global.environment }}"
    RELEASE: "{{ .Release.Name }}"
    MAX_CONN: 100
  feature-flags:
    beta: "false"

global:
  environment: dev
